### ISSUE TITLE
[Feature Request] Add support for group limited tags

### ISSUE THREAD

**Issue by SnowCutieOwO** [Kryz-s/MyMessage#1]
``` YAML
group1: # group name, could be anything
  permission: 'mym.perm.group1' # the permission to use this limit
  priority: -1 # when faced with multiple groups, which group of limits should we use first? set to -1 to disable this setting
  mode: 'whitelist' # could be `blacklist` or `whitelist`
  list: # the MiniMessage tags, no brackets `<` or `>` needed
    - 'white'
    - 'red' # <white>, </white> and <red> </red>
```

Could you please consider add groups limit for your plugin? I don't want my players could use all of them :3
